/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_syh_ndkdemo_MainActivity */

#ifndef _Included_com_syh_ndkdemo_MainActivity
#define _Included_com_syh_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_syh_ndkdemo_MainActivity
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_syh_ndkdemo_MainActivity_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_syh_ndkdemo_MainActivity
 * Method:    sendStringToC
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_syh_ndkdemo_MainActivity_sendStringToC
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
